### ISSUE TITLE
solidjs 1.6.0 and sx property question

### ISSUE THREAD

**Issue by AlexNolasco** [swordev/suid#127]
Currently getting '_Cannot redefine property_' when using Box' sx property and Solidjs 1.6.0.  Is there a workaround or recommendation?

`         <Box
            sx={{
              backgroundColor: 'yellow',
            }}
          >
`

[stackblitz example](https://stackblitz.com/edit/angular-9dq3xp?file=src/App.tsx)

**Comment by juanrgm** [comment]
https://github.com/swordev/suid/issues/124#issuecomment-1287942523

**Comment by AlexNolasco** [comment]
See also
[Duplicate ](https://github.com/solidjs/solid/issues/1301)
