### ISSUE TITLE
Menu component gets created too many times in the DOM

### ISSUE THREAD

**Issue by alexss3** [swordev/suid#151]
I've been trying to convert a 3rd party React component to SolidJS with SUID and I've been unable to overcome a strange issue that is happening.  Even though I'm only trying to render one instance of the `<Menu />` component, when it becomes visible in the DOM it is actually created a multitude of times and each instance is overlaid on top of the others.

I did a pretty simple StackBlitz to make sure it was reproducible in its simplest form.
The idea is that you have an input field with an icon as the `startAdornment`, and clicking on that icon reveals the menu with some choices.  This is what I've been trying to convert https://github.com/alexplumb/material-ui-phone-number

My StackBlitz is here 
https://stackblitz.com/edit/angular-xa8mj4?file=src/App.tsx

![image](https://user-images.githubusercontent.com/24757608/205873069-1534c9a9-4253-4fd1-a9ef-c00e01bde901.png)
![image](https://user-images.githubusercontent.com/24757608/205873101-dd27c6f2-ac94-432f-9aa7-ae58fcddb99b.png)

**Comment by juanrgm** [comment]
This is a feature/bug of SolidJS:

https://playground.solidjs.com/anonymous/70155133-f027-41ff-873f-5a9d5c8ca3db

Workarounds:

a) https://stackblitz.com/edit/angular-xa8mj4-dammsa?file=src%2FApp.tsx

```ts
export default function SimpleListMenu() {
  const [open, setOpen] = createSignal(false);

  function StartAdornment() {
    return (
      <div>
        <IconButton onClick={() => setOpen(!open())}>Hi</IconButton>
        <Menu open={open()} MenuListProps={{ role: 'listbox' }}>
          {options.map((option) => (
            <MenuItem>{option}</MenuItem>
          ))}
        </Menu>
      </div>
    );
  }

  return (
    <div>
      <TextField
        InputProps={{
          startAdornment: StartAdornment,
        }}
      />
    </div>
  );
}
```

b) https://stackblitz.com/edit/angular-xa8mj4-2ddsrp?file=src%2FApp.tsx

```ts
export default function SimpleListMenu() {
  const [open, setOpen] = createSignal(false);

  return (
    <div>
      <TextField
        InputProps={{
          startAdornment: (
            <IconButton onClick={() => setOpen(!open())}>Hi</IconButton>
          ),
        }}
      />
      <Menu open={open()} MenuListProps={{ role: 'listbox' }}>
        {options.map((option) => (
          <MenuItem>{option}</MenuItem>
        ))}
      </Menu>
    </div>
  );
}
```
