### ISSUE TITLE
Can't use breakpoints in SX prop

### ISSUE THREAD

**Issue by madaxen86** [swordev/suid#166]
MUI docs:
https://mui.com/system/getting-started/usage/#responsive-values

When I use it as described the object is returned as the value and is not returned as media queries like in the React version.

**Comment by juanrgm** [comment]
This is already planned on the [roadmap](https://github.com/swordev/suid/blob/main/ROADMAP.md).

**Comment by juanrgm** [comment]
Closed via https://github.com/swordev/suid/commit/ba6f7a4ccc9d9cfa80654b1d09a61ab2766cf8e0.
