### ISSUE TITLE
How to use @suid/codemod as a package

### ISSUE THREAD

**Issue by aquaductape** [swordev/suid#171]
The documentation shows`@suid/codemod` as a cli tool, but is there a way to use as a package?
Something like this?
```js
import {react2solid} from "@suid/codemod"
const reactCode = `<div className="btn"></div>`
const solidCode = react2solid(reactCode)
```

**Comment by juanrgm** [comment]
```ts
import transformReactSource from "@suid/codemod/transforms/transformReactSource";
import applyTransforms from "@suid/codemod/utils/applyTransforms";

const reactCode = `<div className="btn"></div>`
const solidCode = applyTransforms(reactCode, [transformReactSource]);
```

**Comment by aquaductape** [comment]
It would nice for feature users if you could update the codemod https://github.com/swordev/suid/tree/main/packages/codemod README to include this code

> ```ts
> import transformReactSource from "@suid/codemod/transforms/transformReactSource";
> import applyTransforms from "@suid/codemod/utils/applyTransforms";
> 
> const reactCode = `<div className="btn"></div>`
> const solidCode = applyTransforms(reactCode, [transformReactSource]);
> ```
