### ISSUE TITLE
Using styled components and descendant Selectors

### ISSUE THREAD

**Issue by Bersaelor** [swordev/suid#176]
Following is the simpified situation:

```tsx
const Child = styled('div')(({ theme }) => ({
  color: 'red',
}))

const Parent = styled('div')(({ theme }) => ({
  [`& ${Child}`]: {
    color: 'blue',
  }
}))
```

to layout

```tsx
  return (<>
    <Child>
      This text should be red
    </Child>
    <Parent>
      <Child>This text should be blue</Child>
    </Parent>
  </>
  )
```

Unfortunately both texts are red.

How can I select a descendant?

PS: My real goal is to make a descendant appear when the main div is hovered, i.e.:

```tsx
const Child = styled('div')(({ theme }) => ({
  opacity: 0,
}))

const Parent = styled('div')(({ theme }) => ({
  [`&:hover ${Child}`]: {
    opacity: 1,
  }
}))
```

but the colors also didn't work.

**Comment by Bersaelor** [comment]
I mean, we can always use static classnames like so:
```tsx
const Parent = styled('div')(({ theme }) => ({
 //... 
  '& .child': {
    color: 'blue',
  }
}))
```
and
```tsx
    <Parent>
      <Child class='child>This text should be blue</Child>
    </Parent>
```
but that's so unelegant and adds extra verbosity

**Comment by juanrgm** [comment]
The code works correctly, what is the problem?

https://stackblitz.com/edit/angular-ivi8jv?file=src%2FApp.tsx

```ts
import { styled } from '@suid/material/styles';

const Child = styled('div')(({ theme }) => ({
  color: 'red',
}));

const Parent = styled('div')(({ theme }) => ({
  [`& ${Child}`]: {
    color: 'blue',
  },
}));

export default function Example() {
  return (
    <>
      <Child>This text should be red</Child>
      <Parent>
        <Child>This text should be blue</Child>
      </Parent>
    </>
  );
}
```

**Comment by Bersaelor** [comment]
I tried it for hours and it didn't work, thank you for creating the stackblitz.com so I can safe my sanity.

I only ever tried this as a sub-component in the hierarchy of our solid app, not as a standalone app.
And if I just plug the above code in anywhere, I get both texts as red.

I'm wondering whether I am importing it wrong, in our code we're doing
```
import styled from "@suid/system/styled";
```

while you did in your answer

```
import { styled } from '@suid/material/styles';
```

**Comment by Bersaelor** [comment]
Alright, the reason was that I was still on `"@suid/material": "^0.8.2"`, after upgrading to `"@suid/material": "^0.10.1"` it works now :)
