### ISSUE TITLE
Replace curl and 7z with cross platform tools

### ISSUE THREAD

**Issue by nrayburn-tech** [swordev/suid#177]
Instead of `curl`, `fetch` can be used since Node.js 18+ is required for development.  `https` from Node.js could also be used instead.
https://github.com/swordev/suid/blob/main/scripts/actions/downloadMaterialSource.ts#L16

Instead of `7z`, an NPM package like [yauzl](https://github.com/thejoshwolfe/yauzl) could be used for it to work on different platforms.
https://github.com/swordev/suid/blob/main/scripts/actions/extractMaterialSource.ts#L14

Happy to submit a PR if either of these suggestions are wanted.

**Comment by juanrgm** [comment]
Closed by https://github.com/swordev/suid/commit/47fbe71342bcef8300742cab756cca27301917ee.
