### ISSUE TITLE
Will there be a date picker component in the SUID library?

### ISSUE THREAD

**Issue by gabrielmfern** [swordev/suid#185]
I've seen that in the MUI React library there are [Date Pickers](https://mui.com/x/react-date-pickers/date-picker/), but not in SUID. Could not find it on the roadmap either. Is there any plans to implement Date Pickers? 
If there are any plans, can you tell me maybe what is priority before it, and when it would be out in a new release?

**Comment by juanrgm** [comment]
Duplicated (https://github.com/swordev/suid/issues/130).
