### ISSUE TITLE
How to prevent styles being removed prematurely?

### ISSUE THREAD

**Issue by evertheylen** [swordev/suid#187]
I am using an [AutoAnimate](https://auto-animate.formkit.com/)-esque library. When Solid removes an element, this library will not just let it disappear but instead it will perform an fade-out/shrink animation so it looks better. However, it seems that when Solid considers the element gone and it was the last element of its type, SUID will remove the styles for it. This causes the element to revert back to its default style during the fade-out animation.

If this is unclear, I made a [simple demo on stackblitz](https://stackblitz.com/edit/angular-h6ujvd?file=src%2FApp.tsx). If you toggle and the red text fades out, it remains red as there is another `<RedText>` on the page. But when the green text is supposed to fade out, it "forgets" the styles from `<GreenText>` and reverts to black.

To my knowledge this happens both in development mode as well as in a production build. How can I fix this?

**Comment by evertheylen** [comment]
It's this line: https://github.com/swordev/suid/blob/main/packages/styled-engine/src/createStyle.tsx#L122

Of course Solid will call the onCleanup function if the element gets removed. I'm wondering if we can run the cleanup only when the element itself gets removed from the DOM?

**Comment by juanrgm** [comment]
https://stackblitz.com/edit/angular-h6ujvd-xdvmdv?file=src%2FApp.tsx

```ts
  createEffect((prevStyles: string[] = []) => {
    const resolved = resolvedChildren
      .toArray()
      .filter((r) => r instanceof HTMLElement) as HTMLElement[];

    const removed = prevResolvedChildren.filter((c) => !resolved.includes(c));

    removed.forEach((c) =>
      c.animate([{ opacity: 1 }, { opacity: 0 }], {
        duration: 4000,
        fill: 'forwards',
      })
    );
    prevResolvedChildren = resolved;
    setActualChildren([
      ...prevStyles.map((style) => <style innerHTML={style} />),
      ...resolved,
      ...removed,
    ]);

    const styleClassPrefix = 'css-';

    return resolved.flatMap((element) =>
      [...element.classList]
        .map(
          (className) =>
            className.startsWith(styleClassPrefix) &&
            className.slice(styleClassPrefix.length)
        )
        .filter((id) => id)
        .map((id) => document.getElementById(id).innerHTML)
    );
  });
```

**Comment by evertheylen** [comment]
It's an interesting solution, but doesn't work for nested elements ([example](https://stackblitz.com/edit/angular-h6ujvd-ryomnt?file=src%2FApp.tsx)). Of course, you could extend your solution to also consider all child elements but at that point I think it's a bit too hacky?

I'm not sure how React does it, but assuming SUID is sufficiently similar to MUI they'd have the same issue. I'll try it out.

If I can ask, what is the benefit of removing styles when they're not used? Is it to reduce the memory usage of the browser? It's the first time I encounter an optimization like it. I was honestly surprised the issue was still present after building for production, I thought it was just a developer mode side-effect.

**Comment by juanrgm** [comment]
The only problem with keeping the style elements is the global styles and I don't know if there could be issues with the SSR. I will investigate it.

**Comment by davidlillge** [comment]
Is there any workaround for the moment?

I habe the same problem with [motion](https://motion.dev/).
It realy seams to be a problem with styled components.

**Comment by davidlillge** [comment]
for the moment I removed motion and use a simple "add/remove class" operation for transitions, and only after the transition is finished, I remove the element.

That mean I can't use <Show> directly and must write a <ShowAnimation> Wrapper.

This is only possible because we are in the beginning of a solidJs transition (from Angular), but I think for larger project this is not a real solution.

I hadn't still figured out how I will handle this for page navigation transitions.
But I think the only way is to write a new <Router> for this behavor by myself too.

**Comment by evertheylen** [comment]
Btw, for other people hitting this issue, you can use the solution made by @juanrgm like this:

```jsx
import { StyledEngineProvider } from "@suid/material";

export const App = () => {
  // somewhere close to the root of your app:
  return (
    <StyledEngineProvider value={{cleanupStyles: false}}>
      {/* ... */}
    </StyledEngineProvider>
  );
}
```

**Comment by DanoTheNerd** [comment]
Yeah, I see the benefit of this, but does it now never clean up?
It seems like if we turn this off, we create memory leaks.

Is there no way to use a kind of manual disposer?

**Comment by evertheylen** [comment]
I think (and some quick manual testing seems to confirm this) that the styles can get reused eventually if they are not disposed. So, as the user moves through your app, they will accumulate styles until *all* of your app's styles are loaded and no styles can be added. No leaks, but there may be unused styles present. To me it doesn't feel like a major problem, it's a bit like loading a big CSS file even if your app is not using all of it at every point.

Disabling `cleanupStyles` makes the whole mechanic of `data-uses` a bit unnecessary, with some performance overhead but probably nothing major.

**Comment by DanoTheNerd** [comment]
Maybe a manual cleanup call that removes all `data-uses=0` after every transition could be it.
But I'm not deep enough into this library to check if this caused problems if I manually delete style elements.

**Comment by DanoTheNerd** [comment]
I have also created a transition state machine for this, that will use Show=false only if the transition is finished.
but for that I musted ban \<Show> and \<For> for all other developers in our team

And banning a native solution from the library feels bad.

Transition libraries don't work like that. For them, it would be easy to provide a "transition end" callback that we can call for cleanup, but using a lifecycle helper that won't work with native elements is a nogo for them.

**Comment by evertheylen** [comment]
I am a bit confused by what you mean. My solution doesn't need to ban `Show` or `For`, you just need to use the lifecycle-versions of them when you intend to animate the entering/exiting of some descendant element. In fact, I consider it crucial that the lifecycle-versions can be mixed with the "normal" versions, as the lifecycle tracking does incur some performance overhead (haven't benchmarked though).

The work I still need to do is just writing `<LifecycleShow>`, `<LifecycleMatch>`, `<LifecycleIndex>`, and some more todos like handling nested lifecycles.

**Comment by DanoTheNerd** [comment]
for example using @solidjs/router and a transition library like solid-transition-group, or @motionone/solid.
In no case, this solution works.

solidjs/router doesn't give you the opportunity to use custom show/hide logic

for this to work, I had to fork solidjs router and every other library that uses a show/hide logic and implement the lifecycle logic by myself.

it took me a whole week to write a custom router that works this way and I can not use any other library because they don't work with that either.

**Comment by DanoTheNerd** [comment]
and sorry for this misleading "ban" argument. I mean it only in a "transition" context. Not for the whole project.

but explaining this to a junior dev why he/she can't use show hide and transition libraries the way, they are documented is hard.
