### ISSUE TITLE
Custom typography variant typings

### ISSUE THREAD

**Issue by martinpengellyphillips** [swordev/suid#191]
Hi - thank you for this library!

I've just been trying to follow the official MUI guide for[ adding a custom typography variant](https://mui.com/material-ui/customization/typography/#adding-amp-disabling-variants). It works just fine, except the typings get messed up. I couldn't figure out how to make the new entry in `createTheme` not have a typing error.

Here's the types I tried for a new `inline` variant:

```
import StyledProps from "@suid/system/styledProps";

declare module "@suid/material/styles" {
  interface TypographyVariants {
    inline: StyledProps;
  }

  interface TypographyVariantsOptions {
    inline?: StyledProps;
  }
}

declare module "@suid/material/Typography" {
  interface TypographyPropsVariantOverrides {
    inline: true;
  }
}
```

And here is the issue. Note that the `TypographyPropsVariantOverrides` appears to work, but not the others.

![Screenshot 2023-03-14 at 21 42 40](https://user-images.githubusercontent.com/214338/225146122-891d3880-80cd-4f8d-8cb4-8d1027457219.png)

**Comment by juanrgm** [comment]
I will move all `*Overrides` interfaces to `@suid/material/styles`.

**Comment by martinpengellyphillips** [comment]
Thank you!
