### ISSUE TITLE
SxProp display property not working with breakpoints

### ISSUE THREAD

**Issue by gustavofrancoporto** [swordev/suid#194]
Hello!

I am trying to using the display SxProp property with breakpoints and I am getting the following error:

> render.js?v=75f3ff87:8 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Array.map (<anonymous>)
    at render.js?v=75f3ff87:8:103
    at Array.flatMap (<anonymous>)
    at renderSelector (render.js?v=75f3ff87:8:68)
    at render (render.js?v=75f3ff87:46:27)
    at renderSelector (render.js?v=75f3ff87:8:12)
    at render (render.js?v=75f3ff87:46:27)
    at renderSelector (render.js?v=75f3ff87:8:12)
    at render (render.js?v=75f3ff87:46:27)
    at renderSelector (render.js?v=75f3ff87:8:12)

I created the project from the `solidjs/templates/ts`, installed SUID and here is my App component:

```javascript
import type { Component } from 'solid-js';
import { Box } from "@suid/material";

const App: Component = () => {
    return (
        <Box
            sx={ {
                backgroundColor: "lightBlue",
                width: {
                    xs: 100,
                    sm: 200,
                    md: 300
                },
                display: {
                    xs: "",
                    sm: "none",
                    md: ""
                }
            } }
        >
            Hello World!
        </Box>
    );
};

export default App;
```

**Comment by juanrgm** [comment]
Closed via https://github.com/swordev/suid/commit/af9e1427697a5aec4313611d7f1fcf1c853e74d1.
