### ISSUE TITLE
SUID types makes typescript indexation too slow.

### ISSUE THREAD

**Issue by webblocksapp** [swordev/suid#207]
I'm needing to import a component interface from SUID in order to extend it to build my own component based on SUID.

The issue is when importing `SuidTextFieldProps` or any `AnySuidComponentProps`, typescript types indexation becomes too slow in vscode, and makes difficult types autocomplete slowing down the development flow. Every time I do a change in the code, any SUID type take too long to re-load.

![ezgif-5-d2181d48ae](https://user-images.githubusercontent.com/45544997/232147928-c3f4ab36-e893-4bba-9546-26ad9243a87b.gif)

**Comment by juanrgm** [comment]
This is a known issue in MUI. I've tried to minimize the performance impact on TypeScript but it's difficult because of its design limitations.

What version of TypeScript and what CPU do you use?

**Comment by webblocksapp** [comment]
Hi @juanrgm thanks for your soon reply.

> This is a known issue in MUI. I've tried to minimize the performance impact on TypeScript but it's difficult because of its design limitations.

I'm currently working on a business project where I'm building a company design system using React MUI. Specifically, we're using version 5.10.11, and I haven't encountered any intellisense issues. We have over 20 components that extend from MUI interfaces.

Those are my machine specs:

MacBook Pro 2020
2,3 GHz Quad-Core Intel Core i7
16 GB 3733 MHz LPDDR4X
TS 4.9.5

**Comment by juanrgm** [comment]
Waiting for TypeScript 5.1 (https://github.com/microsoft/TypeScript/pull/53246).

**Comment by juanrgm** [comment]
If you still have problems, open a new issue.
