### ISSUE TITLE
Styles don't work

### ISSUE THREAD

**Issue by rtritto** [swordev/suid#211]
I did some try with _Button_ and _TextField_ components adding _fullwidth_.

```tsx
<Button sx={{ width: '100%' }}>Click me</Button>
```
OR
```tsx
<Button fullwidth>Click me</Button>
```

The style doesn't change.

### Workaround:
```tsx
<Button style={{ width: '100%' }}>Click me</Button>
```

### Versions
@suid/material: 0.12.1
solid-js: 1.7.5
vite-plugin-ssr: 0.4.123

### Reproduction
[suid-material-styles](https://github.com/rtritto/suid-material-styles)

### Links
[SUID/Material - Button doc](https://suid.io/components/button)

[SUID/Material - Button code](https://github.com/swordev/suid/blob/main/packages/material/src/Button/Button.tsx)

**Comment by rtritto** [comment]
FYI @brillout

**Comment by rtritto** [comment]
Reproduction updated

**Comment by rtritto** [comment]
What is the duplicate issue?

**Comment by juanrgm** [comment]
SSR is not fully supported yet (https://github.com/swordev/suid/issues/139).
