### ISSUE TITLE
Support for passing in ref?

### ISSUE THREAD

**Issue by koolkao** [swordev/suid#221]
I love SolidJS + SUID. One thing that would be helpful is if the SUID components support passing in ref, e.g.

`<Button ref={ref}> `

**Comment by juanrgm** [comment]
`ref` property is supported, what is the problem?

https://stackblitz.com/edit/cndexx?file=src%2FApp.tsx

**Comment by koolkao** [comment]
Sorry I was new to SolidJS and misunderstood the use of ref. I've since built a whole SPA on SolidJS and SUID. I really appreciate your work on SUID, thank you! Will more Material UI components like Tabs and Accordion be added?
