### ISSUE TITLE
Dialog does not auto focus or lock focus

### ISSUE THREAD

**Issue by quasaray** [swordev/suid#225]
When dialogs are opened, they do not gain focus.
This means that esc can't be used to close them, as it does not receive the keyboard events.
This is present on the [alert demo](https://suid.io/components/dialog) on the website, alerts will not close when esc is pressed, but the same [alert example for MUI](https://mui.com/material-ui/react-dialog/#alerts) receives the focus.

It is also possible for the focus to leave the dialog, that may just be because the [focus trap](https://mui.com/base-ui/react-focus-trap/) has not been implemented yet.

**Comment by juanrgm** [comment]
Duplicated (https://github.com/swordev/suid/issues/74).
