### ISSUE TITLE
createTheme and ThemeProvider issues

### ISSUE THREAD

**Issue by g0dzcsgo** [swordev/suid#228]

**Comment by juanrgm** [comment]
Are you using SSR?

**Comment by g0dzcsgo** [comment]
> Are you using SSR?

I am not

**Comment by Mos1ju** [comment]
> Are you using SSR?

Is it creating some complication because I'm using SSR and while aplying ThemeProvider everyting starts to breake

**Comment by juanrgm** [comment]
I need some of code for reviewing.

**Comment by Mos1ju** [comment]
> I need some of code for reviewing.

Ive already changed library but thanks for effort

**Comment by musialny** [comment]
> I need some of code for reviewing.

A single root component used in SSR mode with the ThemeProvider caused hydration errors

**Comment by juanrgm** [comment]
Duplicated (https://github.com/swordev/suid/issues/139).
