### ISSUE TITLE
How to use directives with SUID components?

### ISSUE THREAD

**Issue by Bersaelor** [swordev/suid#237]
So the [solidjs form validation example](https://www.solidjs.com/examples/forms) uses [directives](https://www.solidjs.com/tutorial/bindings_directives).

When I put a `console.log` into the `validate` function it gets printed for:

```jsx
<input
  name="email"
  type="email"
  placeholder="Email"
  required
  use:validate={[emailInValid]}
/>
```

when I however put the `use:validate` on a `<TextField>` nothing happens:

```jsx
<TextField
  name="email"
  type="email"
  placeholder="Email"
  component='input'
  required
  use:validate={[emailInValid]}
/>
```

Is there a trick on how to use directives with suid?

**Comment by juanrgm** [comment]
[SolidJS directives](https://www.solidjs.com/tutorial/bindings_directives)

> Important: use: is detected by the compiler to be transformed, and the function is required to be in scope, so it cannot be part of spreads **or applied to a component**.
