### ISSUE TITLE
Problems with suid/icons color after updating to @suid/material@0.13.2

### ISSUE THREAD

**Issue by Bersaelor** [swordev/suid#239]
We just updated to `@suid/material@0.13.2` and `@suid/icons-material@0.6.6` and had the following problem:

For icons which we color like so:

```jsx
            <PlaylistAddRoundedIcon sx={{ color: 'text.primary' }} />
```

they will still have the primary-text color (white) when run with `npm run dev`:

<img width="727" alt="Screenshot 2023-07-18 at 17 56 45" src="https://github.com/swordev/suid/assets/4517582/f263510f-3d69-417f-af97-f148bb83cda7">

But after we `solid-start build`, the icons suddenly have a black color applied to them:

<img width="817" alt="Screenshot 2023-07-18 at 17 51 08" src="https://github.com/swordev/suid/assets/4517582/66d82c85-cfd6-4d8a-bd5a-c1f6dfbfafd3">

**Comment by juanrgm** [comment]
I can't reproduce the problem: https://stackblitz.com/edit/6zw3ga?file=src%2FApp.tsx

It works in dev and prod mode.

**Comment by Bersaelor** [comment]
Is it possible this is somehow related to SSR?

When deployed our app is half-way rendered on the server and then the client does some final adjustments.
If it was caused by SSR, it would explain why we can also not replicate this on our own machines, only once we deploy it to the server.

**Comment by juanrgm** [comment]
With SSR enabled the result is correct.

I suspect [this commit](https://github.com/swordev/suid/commit/72e8ae5fd510a9267cfef9b1f57b565873dfeb9c) as the cause but I can't recreate the issue.

You can override the commit If you revert [these lines](https://github.com/swordev/suid/commit/72e8ae5fd510a9267cfef9b1f57b565873dfeb9c#diff-2c7cf7da812ea2449c0aa4234db4505ed3dc420c1c23306e05b7e892990582c9R238-R240) by this:

```ts
return $componentType() ? inProps.ownerState : undefined;
```

**Comment by Bersaelor** [comment]
I updated to version `0.14.2` on monday and it seems to have worked now , thank you for your effort with suid @juanrgm !
