### ISSUE TITLE
Select + Dynamic options. Selected dynamic option does not trigger change event.

### ISSUE THREAD

**Issue by dpaniq** [swordev/suid#261]
There is a [playground](https://stackblitz.com/edit/solidjs-templates-kxwzpx?file=src%2FApp.jsx,src%2Fcomponents%2FPost%2FPost.jsx) placed on stackblitz.

---
I am using SolidJS and SUID ( Solid material UI ) library.

I am trying to use the same example as in the SUID documentation.
https://suid.io/components/select

```
import { For, createResource, createSignal } from 'solid-js';
import { Select, MenuItem } from '@suid/material'; // or "solid-ui", based on the library's exports

function Post() {
  const [postsResource, { mutate, refetch }] = createResource(async () => {
    const response = await fetch('https://jsonplaceholder.typicode.com/posts');
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    return response.json();
  });

  // State for the selected option
  const [selectedOption, setSelectedOption] = createSignal('any');

  return (
    <div>
      <h1>Posts</h1>
      {postsResource.loading && <p>Loading...</p>}
      {postsResource.error && <p>Error: {postsResource.error.message}</p>}
       {postsResource.state === 'ready' && (
        <>
          <Select
            // defaultValue={'any'}
            // value={selectedOption()}
            onChange={(e) => {
              console.log('onChange', e.currentTarget);
              setSelectedOption(e.currentTarget.value);
            }}
          >
            <MenuItem value="any">Choose any...</MenuItem>
            <MenuItem value="option1">option1</MenuItem>
            <MenuItem value="option2">option2</MenuItem>
            <For each={postsResource()}>
              {(post) => <MenuItem value={post.id}>{post.title}</MenuItem>}
            </For>
          </Select>
        </>
      }
    </div>
  );
}

export default Post;
```
---
In this case, the Options that have values like any, option1 and option2 (static options) are selectable, but other are not.

Also I should mention, when I use static options (code below) a Select works fine.
```
  const options = [
    {id: 1, label: 'Option 1'},
    {id: 2, label: 'Option 2'},
    {id: 3, label: 'Option 3'},
  ];
```

But when I use dynamic options (fetch, createResource, promise, etc), something goes wrong. There are main problems:

- Chosen Option does not change Select value
- onChange handler always receives similar value
- More than two Select changes cause console errors:
```
MUI: A component is changing the uncontrolled value state of Select to be controlled.
Elements should not switch from uncontrolled to controlled (or vice versa).
Decide between using a controlled or uncontrolled Select element for the lifetime of the component.
The nature of the state is determined during the first render. It's considered controlled if the value is not `undefined`.
```

I tried to:

1. Set a defaultValue to Select;
1. Set a defaultValue to createSignal;
1. Set a tabIndex, because I noticed that in For each MenuItem has tabIndex=-1
![image](https://github.com/swordev/suid/assets/42778511/8604dfb9-ce3a-4c14-95d0-361850af15ee)

---
What my expectations are:

- I should be able to choose any option from the Select

---
There is a [playground](https://stackblitz.com/edit/solidjs-templates-kxwzpx?file=src%2FApp.jsx,src%2Fcomponents%2FPost%2FPost.jsx) placed on stackblitz.

I described an issue on [stackoverflow](https://stackoverflow.com/questions/77032082/dynamic-option-does-not-trigger-the-select-component-in-solidjs-playground-inc) as well.

[Screencast from 09-04-2023 08:37:38 PM.webm](https://github.com/swordev/suid/assets/42778511/f9479222-fc20-4a10-8c42-fae9e7cb56c1)

**Comment by juanrgm** [comment]
I must recreate part of the mechanism responsible for managing the selection values. Thanks for the detailed report.

Duplicated (https://github.com/swordev/suid/issues/223).
