### ISSUE TITLE
Question: What version of mui does suid correspond to ?

### ISSUE THREAD

**Issue by wakaztahir** [swordev/suid#262]
I forked SUID, I wanted to change some things to make my own custom UI library for my packages

1 - Could you please tell me which version of MUI does SUID correspond to ?
2 - Do you have plans to removing the styled system of MUI
3 - Are you going to update to latest MUI in the near future ?

My plans for my library are to introduce helpful alternative API

`Button` -> `FilledButton`, `OutlinedButton`, similarly for TextField, ButtonGroup
`Typography` -> `P1`,`P1`,`H1`,`H2`,`H3`,`H4`,`H5`,`H6`

My next plan is to remove material's styled system and use `solid emotion` or `solid-styled-components` basically a CSS in JS library

**Comment by wakaztahir** [comment]
Also I tried compiling this material library with latest typescript, and a lot of versions of typescript compiler but they were all giving memory errors so I have gone back to using `4.8.4` which works !

**Comment by wakaztahir** [comment]
Looking at the script the MUI version 5.5, There isn't a MUI 5.5

**Comment by juanrgm** [comment]
Indeed, v5.5.0.

- https://github.com/swordev/suid/blob/69728b08c8a0e415cb630826a8c8f657d730d86d/scripts/index.ts#L14
- https://github.com/swordev/suid/blob/69728b08c8a0e415cb630826a8c8f657d730d86d/packages/codemod/src/utils/muiVersion.ts#L1

I would like to advance the version but I would like to first see the direction mui v6 takes.

**Comment by wakaztahir** [comment]
Also, MUI uses emotion in 5 however this library uses mui legacy styled system

**Comment by wakaztahir** [comment]
Hi, If I wanted to upgrade this library to use mui version `5.14` which is the latest stable, how would I do that ?
