### ISSUE TITLE
Vite plugin package peer dependency update considering Vite 5.X.X

### ISSUE THREAD

**Issue by codylindley** [swordev/suid#271]
Any chance we get this peer dependency updated for Vite 5.X.X ?

https://github.com/swordev/suid/blob/96534e8529921e29485b750a7d2bdaac1a3561fa/packages/vite-plugin/package.json#L38

**Comment by tkirda** [comment]
@juanrgm Any plans on making this change?

**Comment by BierDav** [comment]
Would be really great, because vite 5 brings obviously a few groundbreaking advantages over vite 4

**Comment by BierDav** [comment]
Is this now fixed in the latest release: https://github.com/swordev/suid/commit/59555792c6b9d42ee7c91c8ebd90f8f6b5133eb5
