### ISSUE TITLE
Select border/label overlap with empty MenuItem value

### ISSUE THREAD

**Issue by lukexor** [swordev/suid#272]
https://stackblitz.com/edit/hmmgyv?file=src%2FApp.tsx

<img width="534" alt="image" src="https://github.com/swordev/suid/assets/709609/45838c04-b7c0-43c5-9b91-a68b98fa3f6b">

Expected to have a white border around the label similar to when an item is selected with a non-empty value.

<img width="532" alt="image" src="https://github.com/swordev/suid/assets/709609/2ecd405e-4297-4c6f-92db-00dda3d7f1a3">

Digging in it seems like there's a max-width property on the legend component that is normally 100% but switches to 0.01px when the value property is empty.

**Comment by aseerkt** [comment]
You can fix this by passing `notched` prop as `true` to `Select` component.

**Comment by juanrgm** [comment]
It's not a bug, the behavior is the same as MUI.
