### ISSUE TITLE
Drawer variant persistent?

### ISSUE THREAD

**Issue by geohuz** [swordev/suid#275]
It looks like the persistent drawer is not implemented, get the error:

```
Cannot set properties of undefined (setting 'visibility')
```

**Comment by aseerkt** [comment]
Here is working codesandox where persistant drawer is implemented
https://stackblitz.com/edit/kj8ujx?file=src%2FApp.tsx

**Comment by geohuz** [comment]
Sorry I was using solidjs inside Astro, the issue may related to Astro.
