### ISSUE TITLE
Doesn't convert React Fragment to JSX Fragment Tag

### ISSUE THREAD

**Issue by aquaductape** [swordev/suid#28]
In React2Solid converter, if React code has React Fragment `<React.Fragment></React.Fragment>`, it should convert it to JSX Fragment tag `<></>`. Instead it doesn't and output includes React Fragment.

Quick MUI example (with full source toggled) that has React Fragment https://mui.com/components/modal/#nested-modal

**Comment by juanrgm** [comment]
Closed via 7ec9e0ea85da73ba7542cf384f781590ce166605
