### ISSUE TITLE
The description is a bit confusing 

### ISSUE THREAD

**Issue by oliviertassinari** [swordev/suid#30]
I think that we could work on the description of the package, it's a bit confusing on what the port aim to cover:

<img width="425" alt="Screenshot 2022-04-06 at 00 33 09" src="https://user-images.githubusercontent.com/3165635/161861911-45bfb241-181e-4f05-8f46-7d632a539ba2.png">

If this helps:  MUI (company)

- **a. MUI Core** (product line) - the only React UI library you need, foundational building blocks.
    - i. Pre-made UI libraries (products)
        - Material UI - foundational building blocks, based on Material Design
        - Joy UI - Material UI’s components reimagined with a slick new design (not MD based)
    - ii. MUI Base (product) - Unstyled React components.
    - iii. MUI System (product) - CSS utilities for rapidly laying out custom designs.
- **b. MUI X** (product) - Advanced React components
    - i. Data grid (feature)
    - ii. Date picker (feature)
- **c. MUI Toolpad** (product) - Open source, Low-code internal tool builder.
Drag and drop pre-built components, connect to data sources, and APIs and build simple apps 10x faster.
https://twitter.com/dan_abramov/status/1508267869263515650

---

The port seems to work well, impressed

**Comment by juanrgm** [comment]
True. A better message might be:

> A port of MUI Core (Material-UI) built with Solid.js

**Comment by oliviertassinari** [comment]
Alright, the intent seems clearer, so primarily Material UI. I would personally find it very clear like this:

> A port of Material UI (by MUI) built with Solid.js

**Comment by juanrgm** [comment]
The MUI repository says: 
> MUI Core (formerly Material-UI) is the React UI library you always wanted. Follow your own design system, or start with Material Design.

So other option it would be:

> A port of Material-UI ([MUI](https://mui.com/core)) built with [Solid.js](https://solidjs.com)

Thanks for your feedback!
