### ISSUE TITLE
Setting 'fontFamily' on specific Typography variants does nothing

### ISSUE THREAD

**Issue by evertheylen** [swordev/suid#47]
Maybe similar to #46?

This time I have a slightly more complex theme:

```ts
const theme = createTheme({
  typography: {
    fontFamily: 'monospace',
    h1: {
      fontFamily: 'serif',
      color: 'red',
    },
  },
});
```

I expect that `<Typography variant="h1">Foobar</Typography>` is displayed in red, in a serif font. However, the font remains monospace (but red).

SUID demo: https://stackblitz.com/edit/solid-gp9xzq-vcyyhr?file=src/index.tsx

MUI demo (that works): https://stackblitz.com/edit/react-ca5cbq-nncjf1?file=index.tsx

**Comment by evertheylen** [comment]
Similarly (I can create a new bug if you want), `textTransform` doesn't seem to work either.

SUID demo: https://stackblitz.com/edit/solid-gp9xzq-tjsed5?file=src/index.tsx

MUI demo: https://stackblitz.com/edit/react-ca5cbq-zkhn93?file=index.tsx

**Comment by evertheylen** [comment]
I narrowed it down a little. I can make both `textTransform` and `fontFamily` work by *also* specifying the kebab-case version. (Typescript doesn't like it though.) In other words, this is my theme now:

```ts
const theme = createTheme({
  typography: {
    fontFamily: 'monospace',
    h1: {
      fontFamily: 'serif',
      "font-family": 'serif',
      color: 'red',
    },
    button: {
      textTransform: 'none',
      "text-transform": 'none',
    },
  },
});
```

**Comment by juanrgm** [comment]
There was another problem with the `merge` function (https://github.com/swordev/suid/commit/e003704af0bed136188314d8e38964a66d5f8d08).

Now all is fixed, thanks for your feedback.

Closed via https://github.com/swordev/suid/commit/0bbdd9b714866cbcd4de246e895c1ac9eac3fd31

**Comment by BierDav** [comment]
I can still reproduce the error with solid start
