### ISSUE TITLE
styled is looking for React (wrong import)

### ISSUE THREAD

**Issue by ldlac** [swordev/suid#61]
I just stumbled on a weird behavior, let me know if it's me.

this import `import styled from "@suid/material/styles/styled";`
breaks with a `ReferenceError: React is not defined` in `@suid/system/createStyled.jsx`

when I use this one `import styled from "@suid/system/styled";` 
everything is fine

any idea? should we be able to import the one from material/styles?

**Comment by juanrgm** [comment]
Closed via 167dbcec69bc70a1211d856f595d6ce2ff8ead93.
