### ISSUE TITLE
ListItemButton has no focus style

### ISSUE THREAD

**Issue by EthanStandel** [swordev/suid#75]

**Comment by juanrgm** [comment]
Could you share a demo in stackblitz?

**Comment by EthanStandel** [comment]
Here's an example straight out of the docs. If you tab through the ListItemButtons, none of them have a focus style, so you can't tell what you're focused on

https://stackblitz.com/run?file=src%2FApp.tsx

And here's regular @mui/material

https://stackblitz.com/run?file=demo.tsx

**Comment by juanrgm** [comment]
Thanks for your feedback!

Next time, press share button on stackblitz page for getting a permanent link.

**Comment by EthanStandel** [comment]
Sure thing and oh... duh... that's my bad. Should have been obvious that those weren't permanent from the URLs. I assumed they would work because I litterally just opened up the examples from both projects docs... evidently not 😅 

But thanks for jumping on that so quickly!
