### ISSUE TITLE
Select Component

### ISSUE THREAD

**Issue by agmcleod** [swordev/suid#79]
Hey there, im wondering if the Select component could be added: https://mui.com/material-ui/api/select? Admittedly it's not in the standard material.io components though: https://material.io/components

**Comment by subhasishdas159** [comment]
Need the tab component as well ==> https://mui.com/material-ui/api/tab/

**Comment by chris-czopp** [comment]
Yeah, I personally would find the Select component very useful because I'm going to need in the form builder I've been developing.

**Comment by evlist** [comment]
As a workaround you can use the NativeSelect element I don't see it in the suid documentation but it's implemented (see https://github.com/swordev/suid/tree/main/packages/material/src/NativeSelect).

**Comment by juanrgm** [comment]
This component has been somewhat difficult and it may require some performance tuning later, but it's fully functional.

Closed via 87660200c511cc90e31eb6c2d9f95d686d809dfc.
