### ISSUE TITLE
ThemeProvider is not reactive! (for dark and light switch)

### ISSUE THREAD

**Issue by fmoosavi** [swordev/suid#84]
Hi.
I just started using solid js and found this awesome library and tried to use it.
I think there's a problem with the ThemeProvider! It's not reactive!
I want my app to have a dark/light mode switch, I tried to keep the theme variables in a signal. And it doesn't change after I changed the signal value;
Here's some code:

App.tsx:
```tsx
import { ThemeProvider } from '@suid/material';
import { Component } from 'solid-js';
import { DarkSwitch } from './components/DarkSwitch';
import { Login } from './components/Login';
import { themeSignal } from './utility/Theme';
const App: Component = () => {
  const [theme,setTheme] = themeSignal;
  return <ThemeProvider theme={theme()}>
    <DarkSwitch />
    <Login />
  </ThemeProvider>;
};

export default App;
```

Theme.tsx (the theme signal):
```tsx
import { createTheme } from "@suid/material";
import { createSignal } from "solid-js";

export const darkTheme = createTheme({
    palette: {
        mode: 'dark'
    },
});
export const lightTheme = createTheme({
    palette: {
        mode: 'light'
    },
})
export const themeSignal = createSignal(lightTheme);
```

and the switch button:
```tsx
import DarkMode from '@suid/icons-material/DarkMode';
import LightMode from '@suid/icons-material/LightMode';
import IconButton from "@suid/material/IconButton";
import { Component, createEffect } from "solid-js";
import { darkTheme, lightTheme, themeSignal } from "../utility/Theme";

export const DarkSwitch: Component = () => {
    const [theme, setTheme] = themeSignal;
    createEffect(() => {
        console.log(theme().palette.mode);
    });
    return <IconButton onClick={() => setTheme(theme().palette.mode === 'dark' ? lightTheme : darkTheme)}>
        {theme().palette.mode === 'dark' ? <LightMode /> : <DarkMode />}
    </IconButton>;
};
```
And the dark mode toggle doesn't work although it does update the theme, the provider doesn't get the change.

What I think is the provider should pass the signal itself, not the computed value! like below:
```tsx
 const [theme,setTheme] = themeSignal;
  return <ThemeProvider theme={theme}> // <--- this part
    <DarkSwitch />
    <Login />
  </ThemeProvider>;
```

Because all of the reactive systems of solidjs come from sending the signal, not the value.

**Comment by juanrgm** [comment]
It seems that this is not a SUID issue:

https://playground.solidjs.com/?hash=-1696087014&version=1.4.1

I recommend you this practice:

https://github.com/swordev/suid/blob/eae64adc47cc12ac4d65a376b731858d355d4ba5/packages/site/src/layouts/MainLayout/MainLayout.tsx#L50

**Comment by fmoosavi** [comment]
> It seems that this is not a SUID issue:
> 
> https://playground.solidjs.com/?hash=-1696087014&version=1.4.1
> 
> I recommend you this practice:
> 
> https://github.com/swordev/suid/blob/eae64adc47cc12ac4d65a376b731858d355d4ba5/packages/site/src/layouts/MainLayout/MainLayout.tsx#L50

Thanks. to those who saw this page, The fixed solution came to this:

Theme.tsx:
`import { createTheme } from "@suid/material";
import { createPalette } from "@suid/material/styles/createPalette";
import { createEffect, createMemo } from "solid-js";
import { createStore } from 'solid-js/store';
export function getSavedDarkMode() {
    const value = localStorage.getItem("darkMode");
    if (value === "true") return true;
    if (value === "false") return false;
}

function isSysThemeDark() {
    return window.matchMedia("(prefers-color-scheme: dark)").matches;
}
export const [themeContext, setTheme] = createStore({
    darkMode: getSavedDarkMode() ?? isSysThemeDark(),
});

createEffect(()=>{
    localStorage.setItem("darkMode",themeContext.darkMode.toString())
})

const palette = createMemo(() =>
    createPalette({
        mode: themeContext.darkMode ? "dark" : "light",
    })
);


export const theme = createTheme({
    palette
});`



and  the DarkSwitch:
`import DarkMode from '@suid/icons-material/DarkMode';
import LightMode from '@suid/icons-material/LightMode';
import { useTheme } from '@suid/material';
import IconButton from "@suid/material/IconButton";
import { Component, createEffect } from "solid-js";
import { setTheme } from '../utility/Theme';

export const DarkSwitch: Component = () => {
    const theme = useTheme();
    return <IconButton onClick={() => setTheme({darkMode: theme.palette.mode !== 'dark'})}>
        {theme.palette.mode === 'dark' ? <LightMode /> : <DarkMode />}
    </IconButton>;
};`
