### ISSUE TITLE
React to Solid

### ISSUE THREAD

**Issue by blitzd** [swordev/suid#86]
The React to Solid converter [page](https://suid.io/tools/react-to-solid) just seems to output the exact code as is input.

![image](https://user-images.githubusercontent.com/1502984/182173839-2f2786c6-d366-4807-bbf4-5404dc621927.png)

**Comment by juanrgm** [comment]
Them problem is the `esm.sh` cache.

The `code-writer-block` package was cached with a failure version ([11.0.2](https://esm.sh/v89/code-block-writer@11.0.2)) when it really should be [11.0.3](https://github.com/dsherret/ts-morph/blob/15.1.0/packages/ts-morph/package.json#L48).
