### ISSUE TITLE
ButtonBase throwing error

### ISSUE THREAD

**Issue by T3ch0o** [swordev/suid#92]
ButtonBase is throwing an error never seen it before after updating to 1.5 solidjs but i think that's not the case

MUI: The `component` prop provided to ButtonBase is invalid.
Please make sure the children prop is rendered in this custom component.

I even see it in the playground and the component is unusable.

**Comment by codylindley** [comment]
I am seeing same issue:

![image](https://user-images.githubusercontent.com/115456/187717548-eb4bf207-408d-40f6-b0c2-7c768cf7bcd1.png)

**Comment by juanrgm** [comment]
Closed via https://github.com/swordev/suid/commit/b26b7e4eea4834cc3dee519d8e67e81a4727911f.
