### ISSUE TITLE
Grid in <Show> strange behaviour

### ISSUE THREAD

**Issue by T3ch0o** [swordev/suid#94]
When wrapping < Grid item > in < Show > the view bugs out and all children components inside <Grid container> get re-rendered and if they are buttons become unclickable. This behaviour comes with upgrading to Solid 1.5

**Comment by juanrgm** [comment]
Could you share the code? 

We are experimenting some issues with SolidJS 1.5 due to a breaking change, but I'm working in it.

**Comment by T3ch0o** [comment]
> Could you share the code?
> 
> We are experimenting some issues with SolidJS 1.5 due to a breaking change, but I'm working in it.

```
<Grid maxWidth={800} container spacing={0}>
    <Grid item xs={12}>
	<Divider sx={{ mb: 2 }} />
	<Typography variant="h6" textAlign="center">
		Monthly income
	</Typography>
	<Divider sx={{ mb: 2, mt: 2 }} />
	<MonthlyCalendarSelector onDateChange={onDateChange} useGlobal />
    </Grid>
    <Show when={....}>
       <Grid item xs={12}>
	 .......
       </Grid>
    </Show>
</Grid>
```

So when I have some change happening either on the calendar or inside the Show tag it causes rerender of all componenets inside the Grid tag. Usually what is happening on my side the Monthly calendar rerenders every time when i click on a new date because the view updates and some strange behaviour of my Show tag triggers or i don't know what and restarts my calendar and i am stuck on 1 date only.

**Comment by juanrgm** [comment]
Without a reproducible code is difficult do a diagnostic. Seems to be an issue with SolidJS 1.5 and not SUID.

https://stackblitz.com/edit/angular-7tkpvq?file=src/App.tsx
