### ISSUE TITLE
Contributing guide: getting errors

### ISSUE THREAD

**Issue by LucianoVandi** [swordev/suid#95]
Hello. I'd like to contribute but following the how to on the readme I get several errors.

**Node**: v16.17.0
**Pnpm**: 7.9.5
**OS**: macOS Big Sur 11.6.5 (Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64 x86_64)

The command `pnpm install` runs without throwing errors, but when try `pnpm run codemod mui2suid` it return the following errors:

```
Cannot find module '@suid/utils/capitalize' or its corresponding type declarations.
Cannot find module '@suid/utils/uncapitalize' or its corresponding type declarations.
```

Then if I run `pnpm run build` it fails at `vite build`with error: `failed to load config from /Users/Lmt/Projects/Suid-Dev/packages/site/vite.config.js`, but the build step change the error thrown by codemod command to:

`TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///Users/Lmt/Projects/Suid-Dev/packages/codemod/package.json" needs an import assertion of type "json"`

Is it something related to my setup?

**Comment by juanrgm** [comment]
Closed via https://github.com/swordev/suid/commit/c87208c457ae5d4d0e008939af8ae43b9d9de749.
