### ISSUE TITLE
TextField end adornment warning

### ISSUE THREAD

**Issue by T3ch0o** [swordev/suid#99]
When passing any JSX element to input props warning message appears `computations created outside a "createRoot" or "render" will never be disposed` while passing string for example the message seams to be not found.

**Comment by juanrgm** [comment]
How are you passing the element? Code example please.

This is a bad practice in SolidJS 1.5: https://stackblitz.com/edit/angular-sptjut?file=src%2FApp.tsx

You must wrap the element:

```ts
const endAdornment = () => <Component />;
```
